version: "3.9"

services:

  postgres:
    image: 'postgres:14.2'
    environment:
      - 'POSTGRES_DB=blog'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - "db:/var/lib/postgresql/data"

  auth:
    image: 'auth:latest'
    depends_on:
      - postgres
    ports:
      - 3443:3443
    environment:
      - 'POSTGRES_HOST: localhost'

  post:
    image: 'posts:latest'
    depends_on:
      - auth
    ports:
      - 3444:3444
    environment:
      - 'POSTGRES_HOST: localhost'

volumes:
  db: